In [1]:
import pandas as pd

# Verifying the Path of data  to know the jupyter file path (directory) (csv data path)

If you are unsure of your notebook's current working directory, you can run these commands in a code cell to find out:

import os  
print(os.getcwd())

In [2]:
import os

In [3]:
print(os.getcwd())

C:\Users\ACER\Python Project Murtaza

# if the data path is in same location (same as jupyter installed folder or directory)

In [4]:
df=pd.read_csv('customer_shopping_behavior (2).csv')

# if the data path is in different location (not same as jupyter installed folder or directory)

# to update jupyter notebook for any changes
pip install -U notebook

In [5]:
pip install -U notebook

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: notebook in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (7.6.2)
Requirement already satisfied: jupyter-builder<2,>=1.0.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (1.2.2)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (2.28.0)
Requirement already satisfied: jupyterlab<4.7,>=4.6.3 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (4.6.3)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from notebook) (6.5.5)
Requirement already satisfied: jupyter-core in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-builder<2,>=1.0.2->notebook) (5.9.1)
Requirement already satisfied: traitlets in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-builder<2,>=1.0.2->notebook) (5.16.1)
Requirement already satisfied: anyio>=3.1.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (4.13.0)
Requirement already satisfied: argon2-cffi>=21.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (8.9.1)
Requirement already satisfied: jupyter-events>=0.11.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (7.17.1)
Requirement already satisfied: nbformat>=5.3.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (5.11.0)
Requirement already satisfied: packaging>=22.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (26.0)
Requirement already satisfied: prometheus-client>=0.9 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (3.0.5)
Requirement already satisfied: pyzmq>=24 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-server<3,>=2.19.0->notebook) (1.9.0)
Requirement already satisfied: async-lru>=1.0.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab<4.7,>=4.6.3->notebook) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab<4.7,>=4.6.3->notebook) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab<4.7,>=4.6.3->notebook) (7.3.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab<4.7,>=4.6.3->notebook) (2.3.1)
Requirement already satisfied: certifi in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.3->notebook) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.3->notebook) (1.0.9)
Requirement already satisfied: idna in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.3->notebook) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.3->notebook) (0.16.0)
Requirement already satisfied: babel>=2.10 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (4.26.0)
Requirement already satisfied: requests>=2.31 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.33.1)
Requirement already satisfied: argon2-cffi-bindings in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook) (25.1.0)
Requirement already satisfied: comm>=0.1.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (9.16.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (1.7.2)
Requirement already satisfied: psutil>=5.7 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (7.2.2)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.19.0->notebook) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.19.0->notebook) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.19.0->notebook) (4.15.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-core->jupyter-builder<2,>=1.0.2->notebook) (4.11.2)
Requirement already satisfied: python-json-logger>=2.0.4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (6.0.3)
Requirement already satisfied: rfc3339-validator in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (0.1.1)
Requirement already satisfied: fqdn in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (1.5.1)
Requirement already satisfied: isoduration in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (1.1.0)
Requirement already satisfied: uri-template in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (25.10.0)
Requirement already satisfied: beautifulsoup4 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (6.4.0)
Requirement already satisfied: defusedxml in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (1.5.1)
Requirement already satisfied: webencodings in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->notebook) (2.22.1)
Requirement already satisfied: six>=1.5 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.19.0->notebook) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (1.3.1)
Requirement already satisfied: executing>=1.2.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.3->notebook) (0.2.3)
Requirement already satisfied: cffi>=2.0.0b1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from cffi>=2.0.0b1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook) (2.9.2)
Requirement already satisfied: arrow>=0.15.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (1.4.0)
Requirement already satisfied: tzdata in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (2026.1)
Note: you may need to restart the kernel to use updated packages.

# top 5 rows of data to see how are data looks

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

# to see more details of data like data types, rows , column etc

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

# to check the summary statistics of all the columns (here we will get only numerical columns)

In [8]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

# here we will get both numerical and categorical columns

In [9]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

# # to check the missing values or null values in data

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
''' 
# we will handle missing rating or null values using mean or median 

# generally we should choose median over mean because mean can get affected by outliers and that skew the distribution of 
data

# and why median ? because median is robust to outliers

# now a common beginner will do here is just fill all the missing rating with over all median of entire column and moove on
and yes that technically works but its not the best practice, 

why ? because rating can vary a lot depending on the category like clothing can have different review rating than footware 
category similarly 

# now if we just take the overall median and fill it everywhere, we are basically forcing clothing items to get the same 
review ratings as footware items and that can introduce bias into our data set instead what we will do is a little bit smarter
than that

# we will impute the missing values using the median review rating within each category

# we will find out the median review rating within each category and will replace that with the missing values of the category

# if the clothing item review rating is missing , its gets replaced with median review rating of the clothing items 
not footwear item lets write the code

# we will group it by category, we will use fillna for that to fill it with median
# values within that category.

In [11]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
# now check the missing and null values are left, we have imputed all the null values in the review rating column to clean it 
# this is the right way to clean the data

In [12]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
# data formatting is needed because here available upper case, lower case, speaces we will use snake casing(all lower case)
# and all specaes are replaced by _(underscore)

In [ ]:
# lower case all the columns name
# replace all the spaces with _ (underscore)
# short the long name with suitable name

In [13]:
df.columns = df.columns.str.lower() 
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [ ]:
# lets do some future engineering, add a new column age_group

In [15]:
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [16]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [17]:
# lets do some future engineering, create column purchase_frequency_days

In [17]:
frequency_mapping ={
    
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90    
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [18]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [ ]:
# lets do some future engineering, check above column 'discount_applied' and 'promo_code_used' have same value if its true
# we have to drop one column

In [19]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [20]:
df = df.drop('promo_code_used', axis=1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [22]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------------------------- -------------- 1.8/2.8 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 9.5 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [23]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import pandas as pd

In [ ]:
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine
# step 1 : connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"  # default user
password = "Password@123" # the password you set during installation
host = "localhost" # if running locally
port = "5432" # default postgreSQL port
database = "customer_behavior" # the database you created now 

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [ ]:
table_name = "testtbl"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

In [ ]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [ ]:
print(df.head())

In [ ]:
df.head()

In [ ]:
# code for mysql connection

In [24]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ACER\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [25]:
username = "root"  # default user
password = "Sinu2004" # the password you set during installation
host = "localhost" # if running locally
port = "3306" # default postgreSQL port
database = "project_db" # the database you created now

In [26]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Sinu2004@localhost:3306/project_db"
)

In [27]:
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [ ]:
!pip install pymysql --user

In [ ]:
pip install pymysql

In [ ]:
import pymysql

In [ ]:
print(pymysql.__version__)

In [28]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = quote_plus("Sinu2004")
host = "localhost"
port = 3306
database = "project_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [29]:
with engine.connect() as connection:
    print("MySQL connection successful!")

MySQL connection successful!

In [30]:


# step 2 : load dataframe into postgreSQL
table_name = "testtbl"  # choose any table name
database = "project_db"
df.to_sql(table_name, engine, if_exists = "replace", index = False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'testtbl' in database 'project_db'.

In [ ]:
!pip install psycopg2

In [ ]:
!pip install psycopg2-binary --user

In [ ]:
!pip install psycopg2

In [ ]:
'''python -m venv venv
venv\Scripts\activate
pip install psycopg2-binary'''

if access denied

In [ ]:
!pip install psycopg2

In [ ]:
im